### ISSUE TITLE
import Python modules in py_scripts directory

### ISSUE THREAD

**Issue by vpanchal-code** [naskio/n8n-nodes-python#10]
I have the following a `test.py` script in my py_scripts directory, How can I import the `test.py` script using the python function node.

**Comment by vpanchal-code** [comment]
I tried to change the working dir and then import the `test.py`:
```
import os
os.chdir('/data/py_scripts')
import test
```

But still getting the following error:
```
NodeOperationError: exitCode: 1 Traceback (most recent call last):
  File "/tmp/f18afa421bb8b17da6d18ee9b7643867.py", line 29, in <module>
    fire.Fire(main)
  File "/usr/local/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/usr/local/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/usr/local/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/tmp/f18afa421bb8b17da6d18ee9b7643867.py", line 20, in main
    new_items = snippet_runner(items, env_vars)
  File "/tmp/f18afa421bb8b17da6d18ee9b7643867.py", line 13, in snippet_runner
    import test
ModuleNotFoundError: No module named 'test'

    at Object.execute (/usr/lib/node_modules/n8n/node_modules/n8n-nodes-python/nodes/PythonFunction/PythonFunction.node.ts:107:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Workflow.runNode (/usr/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1263:19)
    at /usr/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:951:29
```
